dist: trusty
language: java
jdk:
  - openjdk7

cache:
  directories:
  - $HOME/.m2

install: "mvn install -s .maven_settings.xml -DskipTests=true -Dmaven.javadoc.skip=true -B"

script: "mvn verify -s .maven_settings.xml -Dmaven.javadoc.skip=true -B"

deploy:
  - provider: script
    script: "mvn deploy -s .maven_settings.xml -DskipTests=true -B"
    on:
      branch: master
      tags: false
